// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIKey - Created
type APIKey struct {
	APIKey string `json:"api_key"`
	Name   string `json:"name"`
}

func (o *APIKey) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *APIKey) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
