// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIKeys - Success
type APIKeys struct {
	Items []APIKey `json:"items"`
}

func (o *APIKeys) GetItems() []APIKey {
	if o == nil {
		return []APIKey{}
	}
	return o.Items
}
