// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConnectionSpecListing - Success
type ConnectionSpecListing struct {
	Items []ConnectionSpec `json:"items"`
	Next  *string          `json:"next,omitempty"`
	Prev  *string          `json:"prev,omitempty"`
}

func (o *ConnectionSpecListing) GetItems() []ConnectionSpec {
	if o == nil {
		return []ConnectionSpec{}
	}
	return o.Items
}

func (o *ConnectionSpecListing) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ConnectionSpecListing) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}
