// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GrantWorkflow struct {
	Steps []Step `json:"steps"`
}

func (o *GrantWorkflow) GetSteps() []Step {
	if o == nil {
		return []Step{}
	}
	return o.Steps
}
