// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type GrantKitVersion struct {
	CreatedAt    time.Time     `json:"created_at"`
	Description  string        `json:"description"`
	GrantKitID   string        `json:"grant_kit_id"`
	GrantKitName string        `json:"grant_kit_name"`
	ID           string        `json:"id"`
	Output       Output        `json:"output"`
	Policies     Policies      `json:"policies"`
	UpdatedAt    time.Time     `json:"updated_at"`
	Version      int64         `json:"version"`
	Workflow     GrantWorkflow `json:"workflow"`
}

func (o *GrantKitVersion) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *GrantKitVersion) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *GrantKitVersion) GetGrantKitID() string {
	if o == nil {
		return ""
	}
	return o.GrantKitID
}

func (o *GrantKitVersion) GetGrantKitName() string {
	if o == nil {
		return ""
	}
	return o.GrantKitName
}

func (o *GrantKitVersion) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GrantKitVersion) GetOutput() Output {
	if o == nil {
		return Output{}
	}
	return o.Output
}

func (o *GrantKitVersion) GetPolicies() Policies {
	if o == nil {
		return Policies{}
	}
	return o.Policies
}

func (o *GrantKitVersion) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *GrantKitVersion) GetVersion() int64 {
	if o == nil {
		return 0
	}
	return o.Version
}

func (o *GrantKitVersion) GetWorkflow() GrantWorkflow {
	if o == nil {
		return GrantWorkflow{}
	}
	return o.Workflow
}
