// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Identity - Created
type Identity struct {
	CreatedAt time.Time                `json:"created_at"`
	ID        string                   `json:"id"`
	Linked    map[string][]interface{} `json:"linked"`
	Name      string                   `json:"name"`
}

func (o *Identity) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Identity) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Identity) GetLinked() map[string][]interface{} {
	if o == nil {
		return map[string][]interface{}{}
	}
	return o.Linked
}

func (o *Identity) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
