// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RequestContentType string

const (
	RequestContentTypeApplicationJSON               RequestContentType = "application/json"
	RequestContentTypeApplicationXWwwFormUrlencoded RequestContentType = "application/x-www-form-urlencoded"
)

func (e RequestContentType) ToPointer() *RequestContentType {
	return &e
}

func (e *RequestContentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "application/json":
		fallthrough
	case "application/x-www-form-urlencoded":
		*e = RequestContentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RequestContentType: %v", v)
	}
}
