// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ReviewUpdateParams struct {
	Reason string `json:"reason"`
}

func (o *ReviewUpdateParams) GetReason() string {
	if o == nil {
		return ""
	}
	return o.Reason
}
