// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CodeSamples struct {
	// Output string
	Output   *string         `json:"output,omitempty"`
	Registry *SourceRegistry `json:"registry,omitempty"`
}

func (o *CodeSamples) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *CodeSamples) GetRegistry() *SourceRegistry {
	if o == nil {
		return nil
	}
	return o.Registry
}
