// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OverlayCompareResponse - Successful response
type OverlayCompareResponse struct {
	// The studio modifications overlay contents - this should be an overlay YAML document
	Overlay string `json:"overlay"`
}

func (o *OverlayCompareResponse) GetOverlay() string {
	if o == nil {
		return ""
	}
	return o.Overlay
}
