// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OverlayCompareRequestBody struct {
	// The first yaml file
	Before string `json:"before"`
	// The second yaml file
	After string `json:"after"`
}

func (o *OverlayCompareRequestBody) GetBefore() string {
	if o == nil {
		return ""
	}
	return o.Before
}

func (o *OverlayCompareRequestBody) GetAfter() string {
	if o == nil {
		return ""
	}
	return o.After
}
