// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunRequestBody struct {
	// The studio modifications overlay contents - this should be an overlay YAML document
	Overlay string `json:"overlay"`
	// The input spec for the source
	Input string `json:"input"`
	// Map of target specific inputs keyed on target name
	// Only present if a target input is modified
	//
	Targets map[string]TargetSpecificInputs `json:"targets"`
}

func (o *RunRequestBody) GetOverlay() string {
	if o == nil {
		return ""
	}
	return o.Overlay
}

func (o *RunRequestBody) GetInput() string {
	if o == nil {
		return ""
	}
	return o.Input
}

func (o *RunRequestBody) GetTargets() map[string]TargetSpecificInputs {
	if o == nil {
		return map[string]TargetSpecificInputs{}
	}
	return o.Targets
}
