// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunStreamOptions struct {
	// whether to send a progress update at each generation step
	Steps bool `json:"steps"`
}

func (o *RunStreamOptions) GetSteps() bool {
	if o == nil {
		return false
	}
	return o.Steps
}
