// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Secret string `security:"scheme,type=apiKey,subtype=header,name=x-secret-key"`
}

func (o *Security) GetSecret() string {
	if o == nil {
		return ""
	}
	return o.Secret
}
