// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SourceResponseData struct {
	// Source ID in the workflow file
	SourceID string `json:"sourceID"`
	// The merged input specs for the source
	Input string `json:"input"`
	// Studio modifications overlay contents (could be empty string)
	Overlay string `json:"overlay"`
	// Studio modifications overlay path
	OverlayPath string `json:"overlayPath"`
	// Result of running the source in the workflow
	Output string `json:"output"`
	// List of validation errors
	Diagnosis []Diagnostic `json:"diagnosis,omitempty"`
}

func (o *SourceResponseData) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

func (o *SourceResponseData) GetInput() string {
	if o == nil {
		return ""
	}
	return o.Input
}

func (o *SourceResponseData) GetOverlay() string {
	if o == nil {
		return ""
	}
	return o.Overlay
}

func (o *SourceResponseData) GetOverlayPath() string {
	if o == nil {
		return ""
	}
	return o.OverlayPath
}

func (o *SourceResponseData) GetOutput() string {
	if o == nil {
		return ""
	}
	return o.Output
}

func (o *SourceResponseData) GetDiagnosis() []Diagnostic {
	if o == nil {
		return nil
	}
	return o.Diagnosis
}
