// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ValidationError struct {
	// Error message
	Message string `json:"message"`
	// Error severity
	Severity string `json:"severity"`
	// Line number
	Line int64 `json:"line"`
	// Error type
	Type string `json:"type"`
	// Help message
	HelpMessage *string `json:"helpMessage,omitempty"`
}

func (o *ValidationError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *ValidationError) GetSeverity() string {
	if o == nil {
		return ""
	}
	return o.Severity
}

func (o *ValidationError) GetLine() int64 {
	if o == nil {
		return 0
	}
	return o.Line
}

func (o *ValidationError) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *ValidationError) GetHelpMessage() *string {
	if o == nil {
		return nil
	}
	return o.HelpMessage
}
