workflowVersion: 1.0.0
sources:
    SpeakeasyStudio-OAS:
        inputs:
            - location: ../oas_studio.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay-1.yaml
            - location: .speakeasy/speakeasy-modifications-overlay-2.yaml
            - location: .speakeasy/speakeasy-modifications-overlay-3.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/speakeasy-studio-oas
targets:
    speakeasy-studio:
        target: go
        source: SpeakeasyStudio-OAS
