workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SpeakeasyStudio-OAS:
        inputs:
            - location: /home/qynn/SpeakEasy/speakeasy/internal/studio/oas_studio.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        # registry:
        #     location: registry.speakeasyapi.dev/qynn/qynn-dev/speakeasy-studio-oas
targets:
    speakeasy-studio-go:
        target: go
        source: SpeakeasyStudio-OAS
    speakeasy-studio-ts:
        target: typescript
        source: SpeakeasyStudio-OAS
        output: /home/qynn/SpeakEasy/speakeasy-registry/web/packages/generated-studio-ts-sdk
