workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SpeakeasyStudio-OAS:
        inputs:
            - location: ../oas_studio.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/speakeasy-studio-oas
targets:
    speakeasy-studio-go:
        target: go
        source: SpeakeasyStudio-OAS
    speakeasy-studio-ts:
        target: typescript
        source: SpeakeasyStudio-OAS
        output: /path/to/speakeasy-registry/web/packages/generated-studio-ts-sdk
