version: 2
registries:
  github-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.BOT_REPO_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    # Try to group minor and patch updates for less toil
    groups:
      github-actions-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/"
    # Try to group minor and patch updates for less toil
    groups:
      gomod-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        exclude-patterns:
          # Does not necessarily follow semver, raise individual PR for ease
          - "github.com/speakeasy-api/speakeasy-core"
        update-types:
          - minor
          - patch
    ignore:
      # Updated via ./scripts/upgrade.bash
      - dependency-name: "github.com/speakeasy-api/openapi-generation/v2"
    registries:
       - github-private
    schedule:
      interval: weekly
