version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    # Try to group minor and patch updates for less toil
    groups:
      github-actions-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/"
    # Try to group minor and patch updates for less toil
    groups:
      gomod-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
    ignore:
      # Ignore private repositories for now. Consider private git "registries"
      # configuration if we do want to automate these.
      - dependency-name: "github.com/speakeasy-api/jsonpath"
      - dependency-name: "github.com/speakeasy-api/speakeasy-core"
      # Updated via ./scripts/upgrade.bash
      - dependency-name: "github.com/speakeasy-api/openapi-generation/v2"
    schedule:
      interval: weekly
