workflowVersion: 1.0.0
sources:
    SpekaeasyStudio-OAS:
        inputs:
            - location: ../oas_studio.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/spekaeasy-studio-oas
targets:
    spekaeasy-studio:
        target: go
        source: SpekaeasyStudio-OAS
