// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// StatusGetXSpeakeasyErrors501ApplicationJSON - Not Implemented
type StatusGetXSpeakeasyErrors501ApplicationJSON struct {
	RawResponse *http.Response `json:"-"`
	Code        *string        `json:"code,omitempty"`
	Message     *string        `json:"message,omitempty"`
}

var _ error = &StatusGetXSpeakeasyErrors501ApplicationJSON{}

func (e *StatusGetXSpeakeasyErrors501ApplicationJSON) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
