version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
linters:
  default: none
  enable:
    # - copyloopvar
    # - durationcheck
    # - errcheck
    # - forcetypeassert
    # - gocheckcompilerdirectives
    - govet
    # - ineffassign
    # - intrange
    # - loggercheck
    # - makezero
    # - mirror
    - misspell
    # - nilerr
    # - nolintlint
    # - perfsprint
    # - prealloc
    # - predeclared
    # - spancheck
    # - staticcheck
    # - testifylint
    # - unconvert
    # - unparam
    # - unused
    # - usestdlibvars
    # - usetesting
    - wastedassign
