# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.artifactArch={{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: speakeasy
    tap:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://www.speakeasyapi.dev
    description: The Speakeasy CLI for interacting with the Speakeasy Platform
    license: Apache-2.0
    test: |
      system "#{bin}/speakeasy --version"
  - name: speakeasy@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    tap:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://www.speakeasyapi.dev
    description: The Speakeasy CLI for interacting with the Speakeasy Platform
    license: Apache-2.0
    test: |
      system "#{bin}/speakeasy --version"

chocolateys:
  - name: speakeasy
    title: Speakeasy CLI
    authors: Speakeasy Inc
    project_url: https://github.com/speakeasy-api/speakeasy
    url_template: "https://github.com/speakeasy-api/speakeasy/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: 2023 Speakeasy, Inc
    license_url: https://github.com/speakeasy-api/speakeasy/blob/main/LICENSE
    project_source_url: https://github.com/speakeasy-api/speakeasy
    docs_url: https://speakeasyapi.dev/docs/speakeasy-cli
    bug_tracker_url: https://github.com/speakeasy-api/speakeasy/issues
    tags: openapi api codegen validation speakeasy llm client-libraries sdks
    summary: Speakeasy CLI makes validating API specs and generating idiomatic SDKs easy!
    description: |-
      This CLI is a tool for interacting with the Speakeasy platform - the CLI brings the functionality of Speakeasy into your development workflow. It can be run locally or in your CI/CD pipeline to validate your API specs, generate SDKs and more.

      Current functions of the CLI include:

      Generating idiomatic client SDKs from OpenAPI3.X specs:
      Live: Go, Python3, Typescript(Node), Java, PHP, Ruby, Terraform
      Validating the correctness of OpenAPI3 specs. The CLI has a built in command to validate your spec and post helpful error messages.
      Authenticating with the platform and managing API keys.
    release_notes: "https://github.com/speakeasy-api/speakeasy/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
