# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - go run scripts/completions.go
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64  # Windows ARM64 can be enabled if needed
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.artifactArch={{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
    files:
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - id: speakeasy
    dockerfile: Dockerfile
    ids: [speakeasy]
    images:
      - ghcr.io/speakeasy-api/speakeasy
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .Commit }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.created: "{{ .Date }}"

brews:
  - name: speakeasy
    repository:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://www.speakeasy.com
    description: The Speakeasy CLI for interacting with the Speakeasy Platform
    license: Apache-2.0
    test: |
      system "#{bin}/speakeasy --version"
    extra_install: |
      bash_completion.install "completions/speakeasy.bash" => "speakeasy"
      zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
      fish_completion.install "completions/speakeasy.fish"

  - name: speakeasy@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    repository:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://www.speakeasy.com
    description: The Speakeasy CLI for interacting with the Speakeasy Platform
    license: Apache-2.0
    test: |
      system "#{bin}/speakeasy --version"
    extra_install: |
      bash_completion.install "completions/speakeasy.bash" => "speakeasy"
      zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
      fish_completion.install "completions/speakeasy.fish"

chocolateys:
  - name: speakeasy
    title: Speakeasy CLI
    authors: Speakeasy Inc
    project_url: https://github.com/speakeasy-api/speakeasy
    url_template: "https://github.com/speakeasy-api/speakeasy/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: 2024 Speakeasy, Inc
    license_url: https://github.com/speakeasy-api/speakeasy/blob/main/LICENSE
    project_source_url: https://github.com/speakeasy-api/speakeasy
    docs_url: https://speakeasy.com/docs/speakeasy-cli
    bug_tracker_url: https://github.com/speakeasy-api/speakeasy/issues
    tags: openapi api codegen validation speakeasy llm client-libraries sdks
    summary: Speakeasy CLI makes validating API specs and generating idiomatic SDKs easy!
    description: |-
      This CLI is a tool for interacting with the Speakeasy platform - the CLI brings the functionality of Speakeasy into your development workflow. It can be run locally or in your CI/CD pipeline to validate your API specs, generate SDKs and more.

      Current functions of the CLI include:

      Generating idiomatic client SDKs from OpenAPI3.X specs:
      Live: Go, Python3, Typescript(Node), Java, PHP, Ruby, Terraform
      Validating the correctness of OpenAPI3 specs. The CLI has a built in command to validate your spec and post helpful error messages.
      Authenticating with the platform and managing API keys.
    release_notes: "https://github.com/speakeasy-api/speakeasy/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
winget:
  - name: speakeasy
    publisher: Speakeasy
    short_description: Speakeasy CLI makes validating API specs and generating idiomatic SDKs easy!
    license_url: "https://github.com/speakeasy-api/speakeasy/blob/main/LICENSE"
    license: "elastic"
    publisher_url: https://www.speakeasy.com
    publisher_support_url: https://github.com/speakeasy-api/speakeasy/issues
    homepage: https://www.speakeasy.com
    description: |-
      This CLI is a tool for interacting with the Speakeasy platform - the CLI brings the functionality of Speakeasy into your development workflow. It can be run locally or in your CI/CD pipeline to validate your API specs, generate SDKs and more.

      Current functions of the CLI include:

      Generating idiomatic client SDKs from OpenAPI 3.x specs:
      Live: Go, Python3, Typescript(Node), Java, PHP, Ruby, Terraform
      Validating the correctness of OpenAPI3 specs. The CLI has a built in command to validate your spec and post helpful error messages.
      Authenticating with the platform and managing API keys.
    copyright: 2024 Speakeasy, Inc
    skip_upload: auto
    release_notes: "https://github.com/speakeasy-api/speakeasy/releases/tag/v{{ .Version }}"
    release_notes_url: "https://github.com/speakeasy-api/speakeasy/releases/tag/v{{ .Version }}"

    repository:
      owner: speakeasy-api
      name: winget-pkgs
      branch: "speakeasy-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
