// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// Error - Authentication Failed
type Error struct {
	RawResponse *http.Response `json:"-"`
	Code        string         `json:"code"`
	DocURL      *string        `json:"doc_url,omitempty"`
	Message     string         `json:"message"`
	Param       *string        `json:"param,omitempty"`
	Type        string         `json:"type"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
