openapi: 3.1.0
info:
  title: Normalize-Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    test:
      type: string