package git

import (
	"context"
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/google/go-github/v63/github"
	config "github.com/speakeasy-api/sdk-gen-config"
	"github.com/speakeasy-api/speakeasy/internal/ci/environment"
	"github.com/speakeasy-api/speakeasy/internal/ci/logging"
	"github.com/speakeasy-api/speakeasy/internal/ci/telemetry"
	"github.com/speakeasy-api/speakeasy/internal/ci/utils"
	"github.com/speakeasy-api/speakeasy/internal/ci/releases"
)

//go:embed goreleaser.yml
var tfGoReleaserConfig string

const PublishingCompletedString = "Publishing Completed"

func (g *Git) SetReleaseToPublished(version, directory string) error {
	if g.repo == nil {
		return fmt.Errorf("repo not cloned")
	}
	tag := "v" + version
	if directory != "" && directory != "." && directory != "./" {
		tag = fmt.Sprintf("%s/%s", directory, tag)
	}

	release, _, err := g.client.Repositories.GetReleaseByTag(context.Background(), os.Getenv("GITHUB_REPOSITORY_OWNER"), GetRepo(), tag)
	if err != nil {
		return fmt.Errorf("failed to get release for tag %s: %w", tag, err)
	}

	if release != nil && release.ID != nil {
		if release.Body != nil && !strings.Contains(*release.Body, PublishingCompletedString) {
			body := *release.Body + "\n\n" + PublishingCompletedString
			release.Body = &body
		}

		if _, _, err = g.client.Repositories.EditRelease(context.Background(), os.Getenv("GITHUB_REPOSITORY_OWNER"), GetRepo(), *release.ID, release); err != nil {
			return fmt.Errorf("failed to add to release body for tag %s: %w", tag, err)
		}
	}

	return nil
}

func (g *Git) CreateRelease(oldReleaseContent string, languages map[string]releases.LanguageReleaseInfo, outputs map[string]string, targetSpecificReleaseNotes releases.TargetReleaseNotes) error {
	if g.repo == nil {
		return fmt.Errorf("repo not cloned")
	}

	fmt.Println("Creating release")

	headRef, err := g.repo.Head()
	if err != nil {
		return fmt.Errorf("failed to get head ref: %w", err)
	}

	commitHash := headRef.Hash().String()

	for lang, info := range languages {
		tag := "v" + info.Version
		if info.Path != "" && info.Path != "." && info.Path != "./" {
			tag = fmt.Sprintf("%s/%s", info.Path, tag)
		}

		if lang == "terraform" {
			// Terraform is a special case -- we use go releaser externally to turn this tag into a release.
			err = g.CreateTag("v"+info.Version, commitHash)
			if err != nil {
				return fmt.Errorf("failed to create tag: %w", err)
			}
			// Copy our standard terraform config into /tmp/.goreleaser.yml
			err = os.WriteFile("/tmp/.goreleaser.yml", []byte(tfGoReleaserConfig), 0644)
			if err != nil {
				return fmt.Errorf("failed to write goreleaser config: %w", err)
			}
			cmd := exec.Command("goreleaser", "release", "--clean", "--config", "/tmp/.goreleaser.yml")
			cmd.Dir = filepath.Join(environment.GetWorkspace(), "repo")
			cmd.Env = append(os.Environ(),
				"GORELEASER_PREVIOUS_TAG="+info.PreviousVersion,
				"GORELEASER_CURRENT_TAG="+tag,
				"GITHUB_TOKEN="+environment.GetAccessToken(),
				"GPG_FINGERPRINT="+environment.GetGPGFingerprint(),
			)
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
			if err := cmd.Run(); err != nil {
				return fmt.Errorf("failed to run goreleaser: %w", err)
			}
		} else {
			tagName := github.String(tag)
			releaseBody := oldReleaseContent
			logging.Info("INPUT_ENABLE_SDK_CHANGELOG: %s", environment.GetSDKChangelog())
			logging.Info("targetSpecificReleaseNotes: %v", targetSpecificReleaseNotes)
			logging.Info("targetSpecificReleaseNotes.HasReleaseNotesForTarget(lang): %v", targetSpecificReleaseNotes.HasReleaseNotesForTarget(lang))
			if environment.GetSDKChangelog() == "true" && targetSpecificReleaseNotes.HasReleaseNotesForTarget(lang) {
				releaseBody = targetSpecificReleaseNotes.GetReleaseNotesForTarget(lang)
				fmt.Println(fmt.Sprintf("Release Notes Body: \n%s\n", releaseBody))
			}

			release := &github.RepositoryRelease{
				TagName:         tagName,
				TargetCommitish: github.String(commitHash),
				Name:            github.String(fmt.Sprintf("%s - %s - %s", lang, tag, environment.GetInvokeTime().Format("2006-01-02 15:04:05"))),
				Body:            github.String(fmt.Sprintf(`# Generated by Speakeasy CLI%s`, releaseBody)),
			}
			if info.IsPrerelease() {
				release.Prerelease = github.Bool(true)
				// prereleases shouldn’t become the “latest”:
				release.MakeLatest = github.String("false")
			}
			_, _, err = g.client.Repositories.CreateRelease(context.Background(), os.Getenv("GITHUB_REPOSITORY_OWNER"), GetRepo(), release)

			if err != nil {
				if release, _, err := g.client.Repositories.GetReleaseByTag(context.Background(), os.Getenv("GITHUB_REPOSITORY_OWNER"), GetRepo(), *tagName); err == nil && release != nil {
					if release.Body != nil && strings.Contains(*release.Body, PublishingCompletedString) {
						fmt.Println(fmt.Sprintf("a github release with tag %s has already been published ... skipping publishing", *tagName))
						fmt.Println(fmt.Sprintf("to publish this version again please check with your package managed delete the github tag and release"))
						outputName := utils.OutputTargetPublish(lang)
						if _, ok := outputs[outputName]; ok {
							outputs[outputName] = "false"
						}
					}
					// TODO: Consider deleting and recreating the release if we are moving forward with publishing
					return nil
				}
				// If the release fails, trigger a failed publishing CLI event
				if _, publishEventErr := telemetry.TriggerPublishingEvent(info.Path, "failed", utils.GetRegistryName(lang)); publishEventErr != nil {
					fmt.Printf("failed to write publishing event: %v\n", publishEventErr)
				}

				return fmt.Errorf("failed to create release for tag %s: %w", *tagName, err)
			}

			switch lang {
			case "go":
				// Go has no publishing job, so we publish a CLI event on github release here
				if _, publishEventErr := telemetry.TriggerPublishingEvent(info.Path, "success", utils.GetRegistryName(lang)); publishEventErr != nil {
					fmt.Printf("failed to write publishing event: %v\n", publishEventErr)
				}
			case "mcp-typescript":
				// This target should always upload the MCP binaries to the release
				outputs[utils.OutputTargetMCPRelease(lang)] = *tagName
			case "typescript":
				if err := g.AttachMCPReleaseTag(info.Path, *tagName, outputs); err != nil {
					fmt.Printf("attempted to tag standalone MCP binary: %v\n", err)
				}
			}
		}
	}

	return nil
}

func (g *Git) AttachMCPReleaseTag(path, tagName string, outputs map[string]string) error {
	loadedCfg, err := config.Load(filepath.Join(environment.GetWorkspace(), "repo", path))
	if err != nil {
		return err
	}
	if tsConfig, ok := loadedCfg.Config.Languages["typescript"]; ok {
		if enable, ok := tsConfig.Cfg["enableMCPServer"].(bool); ok && enable {
			outputs[utils.OutputTargetMCPRelease("typescript")] = tagName
			return nil
		}
	}

	fmt.Println("No MCP server present ... skipping MCP binary tagging")
	return nil
}
