// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Auth struct {
	// Auth header
	AuthHeader string `json:"authHeader"`
	// Auth secret
	AuthSecret string `json:"authSecret"`
}

func (o *Auth) GetAuthHeader() string {
	if o == nil {
		return ""
	}
	return o.AuthHeader
}

func (o *Auth) GetAuthSecret() string {
	if o == nil {
		return ""
	}
	return o.AuthSecret
}
