// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Workflow struct {
	// Workflow version
	Version string `json:"version"`
	// Speakeasy version
	SpeakeasyVersion string `json:"speakeasyVersion"`
	// Map of sources
	Sources map[string]Source `json:"sources"`
	// Map of targets
	Targets map[string]Target `json:"targets"`
}

func (o *Workflow) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

func (o *Workflow) GetSpeakeasyVersion() string {
	if o == nil {
		return ""
	}
	return o.SpeakeasyVersion
}

func (o *Workflow) GetSources() map[string]Source {
	if o == nil {
		return map[string]Source{}
	}
	return o.Sources
}

func (o *Workflow) GetTargets() map[string]Target {
	if o == nil {
		return map[string]Target{}
	}
	return o.Targets
}
