// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LimitOffsetConfig struct {
	Limit  *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Page   *int64 `json:"page,omitempty"`
}

func (o *LimitOffsetConfig) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *LimitOffsetConfig) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *LimitOffsetConfig) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}
