// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MapObjValue - OK
type MapObjValue struct {
	JSON     map[string]SimpleObject `json:"json,omitempty"`
	Required interface{}             `json:"required,omitempty"`
}

func (o *MapObjValue) GetJSON() map[string]SimpleObject {
	if o == nil {
		return nil
	}
	return o.JSON
}

func (o *MapObjValue) GetRequired() interface{} {
	if o == nil {
		return nil
	}
	return o.Required
}
