// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"math/big"
	"openapi/pkg/types"
	"time"
)

// SimpleObjectInt32Enum - An int32 enum property.
type SimpleObjectInt32Enum int

const (
	SimpleObjectInt32EnumFiftyFive              SimpleObjectInt32Enum = 55
	SimpleObjectInt32EnumSixtyNine              SimpleObjectInt32Enum = 69
	SimpleObjectInt32EnumOneHundredAndEightyOne SimpleObjectInt32Enum = 181
)

func (e SimpleObjectInt32Enum) ToPointer() *SimpleObjectInt32Enum {
	return &e
}

func (e *SimpleObjectInt32Enum) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 55:
		fallthrough
	case 69:
		fallthrough
	case 181:
		*e = SimpleObjectInt32Enum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SimpleObjectInt32Enum: %v", v)
	}
}

// SimpleObjectIntEnum - An integer enum property.
type SimpleObjectIntEnum int64

const (
	SimpleObjectIntEnumFirst  SimpleObjectIntEnum = 1
	SimpleObjectIntEnumSecond SimpleObjectIntEnum = 2
	SimpleObjectIntEnumThird  SimpleObjectIntEnum = 3
)

func (e SimpleObjectIntEnum) ToPointer() *SimpleObjectIntEnum {
	return &e
}

func (e *SimpleObjectIntEnum) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		*e = SimpleObjectIntEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SimpleObjectIntEnum: %v", v)
	}
}

// SimpleObject - A simple object that uses all our supported primitive types and enums and has optional properties.
// https://docs.speakeasyapi.dev - A link to the external docs.
type SimpleObject struct {
	// An any property.
	Any       interface{}   `json:"any" header:"name=any" pathParam:"name=any" queryParam:"name=any" form:"name=any" multipartForm:"name=any"`
	Bigint    *big.Int      `json:"bigint,omitempty" header:"name=bigint" pathParam:"name=bigint" queryParam:"name=bigint" form:"name=bigint" multipartForm:"name=bigint"`
	BigintStr *types.BigInt `json:"bigintStr,omitempty" header:"name=bigintStr" pathParam:"name=bigintStr" queryParam:"name=bigintStr" form:"name=bigintStr" multipartForm:"name=bigintStr"`
	// A boolean property.
	Bool bool `json:"bool" header:"name=bool" pathParam:"name=bool" queryParam:"name=bool" form:"name=bool" multipartForm:"name=bool"`
	// An optional boolean property.
	BoolOpt *bool `json:"boolOpt,omitempty" header:"name=boolOpt" pathParam:"name=boolOpt" queryParam:"name=boolOpt" form:"name=boolOpt" multipartForm:"name=boolOpt"`
	// A date property.
	Date types.Date `json:"date" header:"name=date" pathParam:"name=date" queryParam:"name=date" form:"name=date" multipartForm:"name=date"`
	// A date-time property.
	DateTime time.Time `json:"dateTime" header:"name=dateTime" pathParam:"name=dateTime" queryParam:"name=dateTime" form:"name=dateTime" multipartForm:"name=dateTime"`
	// An string based enum
	Enum Enum `json:"enum" header:"name=enum" pathParam:"name=enum" queryParam:"name=enum" form:"name=enum" multipartForm:"name=enum"`
	// A float32 property.
	Float32 float64 `json:"float32" header:"name=float32" pathParam:"name=float32" queryParam:"name=float32" form:"name=float32" multipartForm:"name=float32"`
	// An integer property.
	Int int64 `json:"int" header:"name=int" pathParam:"name=int" queryParam:"name=int" form:"name=int" multipartForm:"name=int"`
	// An int32 property.
	Int32 int `json:"int32" header:"name=int32" pathParam:"name=int32" queryParam:"name=int32" form:"name=int32" multipartForm:"name=int32"`
	// An int32 enum property.
	Int32Enum SimpleObjectInt32Enum `json:"int32Enum" header:"name=int32Enum" pathParam:"name=int32Enum" queryParam:"name=int32Enum" form:"name=int32Enum" multipartForm:"name=int32Enum"`
	// An integer enum property.
	IntEnum SimpleObjectIntEnum `json:"intEnum" header:"name=intEnum" pathParam:"name=intEnum" queryParam:"name=intEnum" form:"name=intEnum" multipartForm:"name=intEnum"`
	// An optional integer property will be null for tests.
	IntOptNull *int64 `json:"intOptNull,omitempty" header:"name=intOptNull" pathParam:"name=intOptNull" queryParam:"name=intOptNull" form:"name=intOptNull" multipartForm:"name=intOptNull"`
	// A number property.
	Num float64 `json:"num" header:"name=num" pathParam:"name=num" queryParam:"name=num" form:"name=num" multipartForm:"name=num"`
	// An optional number property will be null for tests.
	NumOptNull *float64 `json:"numOptNull,omitempty" header:"name=numOptNull" pathParam:"name=numOptNull" queryParam:"name=numOptNull" form:"name=numOptNull" multipartForm:"name=numOptNull"`
	// A string property.
	Str string `json:"str" header:"name=str" pathParam:"name=str" queryParam:"name=str" form:"name=str" multipartForm:"name=str"`
	// An optional string property.
	StrOpt *string `json:"strOpt,omitempty" header:"name=strOpt" pathParam:"name=strOpt" queryParam:"name=strOpt" form:"name=strOpt" multipartForm:"name=strOpt"`
}

func (o *SimpleObject) GetAny() interface{} {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *SimpleObject) GetBigint() *big.Int {
	if o == nil {
		return nil
	}
	return o.Bigint
}

func (o *SimpleObject) GetBigintStr() *types.BigInt {
	if o == nil {
		return nil
	}
	return o.BigintStr
}

func (o *SimpleObject) GetBool() bool {
	if o == nil {
		return false
	}
	return o.Bool
}

func (o *SimpleObject) GetBoolOpt() *bool {
	if o == nil {
		return nil
	}
	return o.BoolOpt
}

func (o *SimpleObject) GetDate() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.Date
}

func (o *SimpleObject) GetDateTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.DateTime
}

func (o *SimpleObject) GetEnum() Enum {
	if o == nil {
		return Enum("")
	}
	return o.Enum
}

func (o *SimpleObject) GetFloat32() float64 {
	if o == nil {
		return 0.0
	}
	return o.Float32
}

func (o *SimpleObject) GetInt() int64 {
	if o == nil {
		return 0
	}
	return o.Int
}

func (o *SimpleObject) GetInt32() int {
	if o == nil {
		return 0
	}
	return o.Int32
}

func (o *SimpleObject) GetInt32Enum() SimpleObjectInt32Enum {
	if o == nil {
		return SimpleObjectInt32Enum(0)
	}
	return o.Int32Enum
}

func (o *SimpleObject) GetIntEnum() SimpleObjectIntEnum {
	if o == nil {
		return SimpleObjectIntEnum(0)
	}
	return o.IntEnum
}

func (o *SimpleObject) GetIntOptNull() *int64 {
	if o == nil {
		return nil
	}
	return o.IntOptNull
}

func (o *SimpleObject) GetNum() float64 {
	if o == nil {
		return 0.0
	}
	return o.Num
}

func (o *SimpleObject) GetNumOptNull() *float64 {
	if o == nil {
		return nil
	}
	return o.NumOptNull
}

func (o *SimpleObject) GetStr() string {
	if o == nil {
		return ""
	}
	return o.Str
}

func (o *SimpleObject) GetStrOpt() *string {
	if o == nil {
		return nil
	}
	return o.StrOpt
}
