// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type TypedObjectOneOfType string

const (
	TypedObjectOneOfTypeTypedObject1 TypedObjectOneOfType = "typedObject1"
	TypedObjectOneOfTypeTypedObject2 TypedObjectOneOfType = "typedObject2"
	TypedObjectOneOfTypeTypedObject3 TypedObjectOneOfType = "typedObject3"
)

type TypedObjectOneOf struct {
	TypedObject1 *TypedObject1
	TypedObject2 *TypedObject2
	TypedObject3 *TypedObject3

	Type TypedObjectOneOfType
}

func CreateTypedObjectOneOfTypedObject1(typedObject1 TypedObject1) TypedObjectOneOf {
	typ := TypedObjectOneOfTypeTypedObject1

	return TypedObjectOneOf{
		TypedObject1: &typedObject1,
		Type:         typ,
	}
}

func CreateTypedObjectOneOfTypedObject2(typedObject2 TypedObject2) TypedObjectOneOf {
	typ := TypedObjectOneOfTypeTypedObject2

	return TypedObjectOneOf{
		TypedObject2: &typedObject2,
		Type:         typ,
	}
}

func CreateTypedObjectOneOfTypedObject3(typedObject3 TypedObject3) TypedObjectOneOf {
	typ := TypedObjectOneOfTypeTypedObject3

	return TypedObjectOneOf{
		TypedObject3: &typedObject3,
		Type:         typ,
	}
}

func (u *TypedObjectOneOf) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	typedObject1 := new(TypedObject1)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&typedObject1); err == nil {
		u.TypedObject1 = typedObject1
		u.Type = TypedObjectOneOfTypeTypedObject1
		return nil
	}

	typedObject2 := new(TypedObject2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&typedObject2); err == nil {
		u.TypedObject2 = typedObject2
		u.Type = TypedObjectOneOfTypeTypedObject2
		return nil
	}

	typedObject3 := new(TypedObject3)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&typedObject3); err == nil {
		u.TypedObject3 = typedObject3
		u.Type = TypedObjectOneOfTypeTypedObject3
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u TypedObjectOneOf) MarshalJSON() ([]byte, error) {
	if u.TypedObject1 != nil {
		return json.Marshal(u.TypedObject1)
	}

	if u.TypedObject2 != nil {
		return json.Marshal(u.TypedObject2)
	}

	if u.TypedObject3 != nil {
		return json.Marshal(u.TypedObject3)
	}

	return nil, nil
}
