// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Data struct {
	// Status of the CLI
	Status *string `json:"status,omitempty"`
}

func (o *Data) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type HealthResponse struct {
	Data *Data `json:"data,omitempty"`
}

func (o *HealthResponse) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o HealthResponse) GetEventEncoding(event string) (string, error) {
	return "application/json", nil
}
