name: Generate Changelog
description: Generates changelog using TriPSs/conventional-changelog-action
inputs:
    github-token:
        required: true
    output-file:
        required: true

runs:
    using: "composite"
    steps:
        - run: |
              git config --global user.name "speakeasybot"
              git config --global user.email "speakeasybot@speakeasy.com"
          shell: bash

        - uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765
          with:
              github-token: ${{ inputs.github-token }}
              output-file: ${{ inputs.output-file }}
              skip-commit: "true"
              skip-on-empty: "true"
              preset: conventionalcommits
