// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy/internal/run/studio/generated-studio-sdk/models/components"
)

type UpdateSourceRequestBody struct {
	// The studio modifications overlay contents - this should be an overlay YAML document
	Overlay string `json:"overlay"`
}

func (o *UpdateSourceRequestBody) GetOverlay() string {
	if o == nil {
		return ""
	}
	return o.Overlay
}

type UpdateSourceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	SourceResponse *components.SourceResponse
}

func (o *UpdateSourceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSourceResponse) GetSourceResponse() *components.SourceResponse {
	if o == nil {
		return nil
	}
	return o.SourceResponse
}
