// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type ApproveReviewRequest struct {
	ReviewUpdateParams shared.ReviewUpdateParams `request:"mediaType=application/json"`
	// The ID of the review to approve
	ReviewID string `pathParam:"style=simple,explode=false,name=review_id"`
}

func (o *ApproveReviewRequest) GetReviewUpdateParams() shared.ReviewUpdateParams {
	if o == nil {
		return shared.ReviewUpdateParams{}
	}
	return o.ReviewUpdateParams
}

func (o *ApproveReviewRequest) GetReviewID() string {
	if o == nil {
		return ""
	}
	return o.ReviewID
}

type ApproveReviewResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	Review      *shared.Review
	StatusCode  int
	RawResponse *http.Response
}

func (o *ApproveReviewResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ApproveReviewResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ApproveReviewResponse) GetReview() *shared.Review {
	if o == nil {
		return nil
	}
	return o.Review
}

func (o *ApproveReviewResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ApproveReviewResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
