// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type DeleteGrantKitRequest struct {
	// The ID of the grant kit or resource to delete
	GrantKitIDOrName string `pathParam:"style=simple,explode=false,name=grant_kit_id_or_name"`
}

func (o *DeleteGrantKitRequest) GetGrantKitIDOrName() string {
	if o == nil {
		return ""
	}
	return o.GrantKitIDOrName
}

type DeleteGrantKitResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	GrantKit    *shared.GrantKit
	StatusCode  int
	RawResponse *http.Response
}

func (o *DeleteGrantKitResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteGrantKitResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeleteGrantKitResponse) GetGrantKit() *shared.GrantKit {
	if o == nil {
		return nil
	}
	return o.GrantKit
}

func (o *DeleteGrantKitResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteGrantKitResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
