// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetGrantKitsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	GrantKits   []shared.GrantKit
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetGrantKitsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGrantKitsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetGrantKitsResponse) GetGrantKits() []shared.GrantKit {
	if o == nil {
		return nil
	}
	return o.GrantKits
}

func (o *GetGrantKitsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGrantKitsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
