// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetGrantByIDRequest struct {
	// The ID of the grant to retrieve
	GrantID string `pathParam:"style=simple,explode=false,name=grant_id"`
}

func (o *GetGrantByIDRequest) GetGrantID() string {
	if o == nil {
		return ""
	}
	return o.GrantID
}

type GetGrantByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Grant       *shared.Grant
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetGrantByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGrantByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetGrantByIDResponse) GetGrant() *shared.Grant {
	if o == nil {
		return nil
	}
	return o.Grant
}

func (o *GetGrantByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGrantByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
