// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetIdentityRequest struct {
	// The ID of the identity to retrieve
	IdentityID string `pathParam:"style=simple,explode=false,name=identity_id"`
}

func (o *GetIdentityRequest) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

type GetIdentityResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Identity    *shared.Identity
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetIdentityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIdentityResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetIdentityResponse) GetIdentity() *shared.Identity {
	if o == nil {
		return nil
	}
	return o.Identity
}

func (o *GetIdentityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIdentityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
