// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetTaskByIDRequest struct {
	// The ID of the task to retrieve
	TaskID string `pathParam:"style=simple,explode=false,name=task_id"`
}

func (o *GetTaskByIDRequest) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

type GetTaskByIDResponse struct {
	ContentType string
	// Authentication Failed
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// Success
	Task *shared.Task
}

func (o *GetTaskByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTaskByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetTaskByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTaskByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTaskByIDResponse) GetTask() *shared.Task {
	if o == nil {
		return nil
	}
	return o.Task
}
