// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type ListRequestsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Requests    []shared.Request
	StatusCode  int
	RawResponse *http.Response
}

func (o *ListRequestsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListRequestsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ListRequestsResponse) GetRequests() []shared.Request {
	if o == nil {
		return nil
	}
	return o.Requests
}

func (o *ListRequestsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListRequestsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
