// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type ListReviewsResponse struct {
	ContentType string
	// Authentication Failed
	Error *shared.Error
	// Success
	Reviews     []shared.Review
	StatusCode  int
	RawResponse *http.Response
}

func (o *ListReviewsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListReviewsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ListReviewsResponse) GetReviews() []shared.Review {
	if o == nil {
		return nil
	}
	return o.Reviews
}

func (o *ListReviewsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListReviewsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
