// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type UpdateGrantKitRequest struct {
	GrantKitUpdateParams shared.GrantKitUpdateParams `request:"mediaType=application/json"`
	// The ID of the grant kit or resource to update
	GrantKitIDOrName string `pathParam:"style=simple,explode=false,name=grant_kit_id_or_name"`
}

func (o *UpdateGrantKitRequest) GetGrantKitUpdateParams() shared.GrantKitUpdateParams {
	if o == nil {
		return shared.GrantKitUpdateParams{}
	}
	return o.GrantKitUpdateParams
}

func (o *UpdateGrantKitRequest) GetGrantKitIDOrName() string {
	if o == nil {
		return ""
	}
	return o.GrantKitIDOrName
}

type UpdateGrantKitResponse struct {
	ContentType string
	// Request Failed
	Error *shared.Error
	// Success
	GrantKit    *shared.GrantKit
	StatusCode  int
	RawResponse *http.Response
}

func (o *UpdateGrantKitResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateGrantKitResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *UpdateGrantKitResponse) GetGrantKit() *shared.GrantKit {
	if o == nil {
		return nil
	}
	return o.GrantKit
}

func (o *UpdateGrantKitResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateGrantKitResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
