// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type ComponentBodyAndParamNoConflictRequest struct {
	ParamStr     string              `queryParam:"style=form,explode=true,name=paramStr"`
	SimpleObject shared.SimpleObject `request:"mediaType=application/json"`
}

func (o *ComponentBodyAndParamNoConflictRequest) GetParamStr() string {
	if o == nil {
		return ""
	}
	return o.ParamStr
}

func (o *ComponentBodyAndParamNoConflictRequest) GetSimpleObject() shared.SimpleObject {
	if o == nil {
		return shared.SimpleObject{}
	}
	return o.SimpleObject
}

// ComponentBodyAndParamNoConflictRes - OK
type ComponentBodyAndParamNoConflictRes struct {
	Args map[string]string `json:"args"`
	// A simple object that uses all our supported primitive types and enums and has optional properties.
	JSON shared.SimpleObject `json:"json"`
}

func (o *ComponentBodyAndParamNoConflictRes) GetArgs() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Args
}

func (o *ComponentBodyAndParamNoConflictRes) GetJSON() shared.SimpleObject {
	if o == nil {
		return shared.SimpleObject{}
	}
	return o.JSON
}

type ComponentBodyAndParamNoConflictResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Res *ComponentBodyAndParamNoConflictRes
}

func (o *ComponentBodyAndParamNoConflictResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ComponentBodyAndParamNoConflictResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ComponentBodyAndParamNoConflictResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ComponentBodyAndParamNoConflictResponse) GetRes() *ComponentBodyAndParamNoConflictRes {
	if o == nil {
		return nil
	}
	return o.Res
}
