// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var ConnectionErrorGetServerList = []string{
	"http://somebrokenapi.broken",
}

type ConnectionErrorGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *ConnectionErrorGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ConnectionErrorGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ConnectionErrorGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
