// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GlobalsQueryParameterGetRequest struct {
	GlobalQueryParam *string `queryParam:"style=form,explode=true,name=globalQueryParam"`
}

func (o *GlobalsQueryParameterGetRequest) GetGlobalQueryParam() *string {
	if o == nil {
		return nil
	}
	return o.GlobalQueryParam
}

type GlobalsQueryParameterGetResArgs struct {
	GlobalQueryParam string `json:"globalQueryParam"`
}

func (o *GlobalsQueryParameterGetResArgs) GetGlobalQueryParam() string {
	if o == nil {
		return ""
	}
	return o.GlobalQueryParam
}

// GlobalsQueryParameterGetRes - OK
type GlobalsQueryParameterGetRes struct {
	Args GlobalsQueryParameterGetResArgs `json:"args"`
}

func (o *GlobalsQueryParameterGetRes) GetArgs() GlobalsQueryParameterGetResArgs {
	if o == nil {
		return GlobalsQueryParameterGetResArgs{}
	}
	return o.Args
}

type GlobalsQueryParameterGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Res *GlobalsQueryParameterGetRes
}

func (o *GlobalsQueryParameterGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GlobalsQueryParameterGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GlobalsQueryParameterGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GlobalsQueryParameterGetResponse) GetRes() *GlobalsQueryParameterGetRes {
	if o == nil {
		return nil
	}
	return o.Res
}
