// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

// IgnoredGenerationGet200ApplicationJSON - A successful response that contains the simpleObject sent in the request body
type IgnoredGenerationGet200ApplicationJSON struct {
	// A simple object that uses all our supported primitive types and enums and has optional properties.
	JSON *shared.SimpleObject `json:"json,omitempty"`
}

func (o *IgnoredGenerationGet200ApplicationJSON) GetJSON() *shared.SimpleObject {
	if o == nil {
		return nil
	}
	return o.JSON
}

type IgnoredGenerationGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A successful response that contains the simpleObject sent in the request body
	IgnoredGenerationGet200ApplicationJSONObject *IgnoredGenerationGet200ApplicationJSON
}

func (o *IgnoredGenerationGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *IgnoredGenerationGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *IgnoredGenerationGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *IgnoredGenerationGetResponse) GetIgnoredGenerationGet200ApplicationJSONObject() *IgnoredGenerationGet200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.IgnoredGenerationGet200ApplicationJSONObject
}
