// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var OpenIDConnectAuthNewServerList = []string{
	"http://localhost:35456",
}

type OpenIDConnectAuthNewSecurity struct {
	OpenIDConnect string `security:"scheme,type=openIdConnect,name=Authorization"`
}

func (o *OpenIDConnectAuthNewSecurity) GetOpenIDConnect() string {
	if o == nil {
		return ""
	}
	return o.OpenIDConnect
}

type OpenIDConnectAuthNewResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *OpenIDConnectAuthNewResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OpenIDConnectAuthNewResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OpenIDConnectAuthNewResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
