// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var PaginationCursorBodyServerList = []string{
	"http://localhost:35456",
}

type PaginationCursorBodyRequestBody struct {
	Cursor int64 `json:"cursor"`
}

func (o *PaginationCursorBodyRequestBody) GetCursor() int64 {
	if o == nil {
		return 0
	}
	return o.Cursor
}

// PaginationCursorBodyRes - OK
type PaginationCursorBodyRes struct {
	NumPages    int64   `json:"numPages"`
	ResultArray []int64 `json:"resultArray"`
}

func (o *PaginationCursorBodyRes) GetNumPages() int64 {
	if o == nil {
		return 0
	}
	return o.NumPages
}

func (o *PaginationCursorBodyRes) GetResultArray() []int64 {
	if o == nil {
		return []int64{}
	}
	return o.ResultArray
}

type PaginationCursorBodyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Res *PaginationCursorBodyRes

	Next func() (*PaginationCursorBodyResponse, error)
}

func (o *PaginationCursorBodyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PaginationCursorBodyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PaginationCursorBodyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PaginationCursorBodyResponse) GetRes() *PaginationCursorBodyRes {
	if o == nil {
		return nil
	}
	return o.Res
}
