// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// PutAnythingIgnoredGeneration200ApplicationJSON - OK
type PutAnythingIgnoredGeneration200ApplicationJSON struct {
	JSON *string `json:"json,omitempty"`
}

func (o *PutAnythingIgnoredGeneration200ApplicationJSON) GetJSON() *string {
	if o == nil {
		return nil
	}
	return o.JSON
}

type PutAnythingIgnoredGenerationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PutAnythingIgnoredGeneration200ApplicationJSONObject *PutAnythingIgnoredGeneration200ApplicationJSON
}

func (o *PutAnythingIgnoredGenerationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAnythingIgnoredGenerationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAnythingIgnoredGenerationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutAnythingIgnoredGenerationResponse) GetPutAnythingIgnoredGeneration200ApplicationJSONObject() *PutAnythingIgnoredGeneration200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PutAnythingIgnoredGeneration200ApplicationJSONObject
}
