// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

var RequestBodyPostApplicationJSONArrayServerList = []string{
	"http://localhost:35456",
}

type RequestBodyPostApplicationJSONArrayResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	SimpleObjects []shared.SimpleObject
}

func (o *RequestBodyPostApplicationJSONArrayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RequestBodyPostApplicationJSONArrayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RequestBodyPostApplicationJSONArrayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RequestBodyPostApplicationJSONArrayResponse) GetSimpleObjects() []shared.SimpleObject {
	if o == nil {
		return nil
	}
	return o.SimpleObjects
}
