// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// RequestBodyPutStringRes - OK
type RequestBodyPutStringRes struct {
	Data string `json:"data"`
}

func (o *RequestBodyPutStringRes) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}

type RequestBodyPutStringResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Res *RequestBodyPutStringRes
}

func (o *RequestBodyPutStringResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RequestBodyPutStringResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RequestBodyPutStringResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RequestBodyPutStringResponse) GetRes() *RequestBodyPutStringRes {
	if o == nil {
		return nil
	}
	return o.Res
}
