// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var RetriesGetServerList = []string{
	"http://localhost:35456",
}

type RetriesGetRequest struct {
	NumRetries *int64 `queryParam:"style=form,explode=true,name=num-retries"`
	RequestID  string `queryParam:"style=form,explode=true,name=request-id"`
}

func (o *RetriesGetRequest) GetNumRetries() *int64 {
	if o == nil {
		return nil
	}
	return o.NumRetries
}

func (o *RetriesGetRequest) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

// RetriesGetRetries - OK
type RetriesGetRetries struct {
	Retries int64 `json:"retries"`
}

func (o *RetriesGetRetries) GetRetries() int64 {
	if o == nil {
		return 0
	}
	return o.Retries
}

type RetriesGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Retries *RetriesGetRetries
}

func (o *RetriesGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RetriesGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RetriesGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RetriesGetResponse) GetRetries() *RetriesGetRetries {
	if o == nil {
		return nil
	}
	return o.Retries
}
