// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
	"openapi/pkg/models/shared"
	"openapi/pkg/types"
	"time"
)

type UsageExamplePostSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

func (o *UsageExamplePostSecurity) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *UsageExamplePostSecurity) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

// UsageExamplePostRequestBody - A request body that contains fields with different formats for testing example generation
type UsageExamplePostRequestBody struct {
	// A field called email that will have emails generated as examples
	Email *string `json:"email,omitempty"`
	// A field formatted as an email that will have emails generated as examples
	FormatEmail *string `json:"formatEmail,omitempty"`
	// A field formatted as a uri that will have uris generated as examples
	FormatURI *string `json:"formatUri,omitempty"`
	// A field formatted as a uuid that will have uuids generated as examples
	FormatUUID *string `json:"formatUuid,omitempty"`
	// A field formatted as a hostname that will have hostnames generated as examples
	Hostname *string `json:"hostname,omitempty"`
	// A field formatted as an ipv4 that will have ipv4s generated as examples
	Ipv4 *string `json:"ipv4,omitempty"`
	// A field formatted as an ipv6 that will have ipv6s generated as examples
	Ipv6 *string `json:"ipv6,omitempty"`
	// A simple object that uses all our supported primitive types and enums and has optional properties.
	SimpleObject *shared.SimpleObject `json:"simpleObject,omitempty"`
	// A field formatted as an unknown that will have random strings generated as examples
	Unknown *string `json:"unknown,omitempty"`
	// A field called uri that will have uris generated as examples
	URI *string `json:"uri,omitempty"`
	// A field called uuid that will have uuids generated as examples
	UUID *string `json:"uuid,omitempty"`
}

func (o *UsageExamplePostRequestBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UsageExamplePostRequestBody) GetFormatEmail() *string {
	if o == nil {
		return nil
	}
	return o.FormatEmail
}

func (o *UsageExamplePostRequestBody) GetFormatURI() *string {
	if o == nil {
		return nil
	}
	return o.FormatURI
}

func (o *UsageExamplePostRequestBody) GetFormatUUID() *string {
	if o == nil {
		return nil
	}
	return o.FormatUUID
}

func (o *UsageExamplePostRequestBody) GetHostname() *string {
	if o == nil {
		return nil
	}
	return o.Hostname
}

func (o *UsageExamplePostRequestBody) GetIpv4() *string {
	if o == nil {
		return nil
	}
	return o.Ipv4
}

func (o *UsageExamplePostRequestBody) GetIpv6() *string {
	if o == nil {
		return nil
	}
	return o.Ipv6
}

func (o *UsageExamplePostRequestBody) GetSimpleObject() *shared.SimpleObject {
	if o == nil {
		return nil
	}
	return o.SimpleObject
}

func (o *UsageExamplePostRequestBody) GetUnknown() *string {
	if o == nil {
		return nil
	}
	return o.Unknown
}

func (o *UsageExamplePostRequestBody) GetURI() *string {
	if o == nil {
		return nil
	}
	return o.URI
}

func (o *UsageExamplePostRequestBody) GetUUID() *string {
	if o == nil {
		return nil
	}
	return o.UUID
}

// UsageExamplePostEnumParameter - An enum type
type UsageExamplePostEnumParameter string

const (
	UsageExamplePostEnumParameterValue1 UsageExamplePostEnumParameter = "value1"
	UsageExamplePostEnumParameterValue2 UsageExamplePostEnumParameter = "value2"
	UsageExamplePostEnumParameterValue3 UsageExamplePostEnumParameter = "value3"
)

func (e UsageExamplePostEnumParameter) ToPointer() *UsageExamplePostEnumParameter {
	return &e
}

func (e *UsageExamplePostEnumParameter) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "value1":
		fallthrough
	case "value2":
		fallthrough
	case "value3":
		*e = UsageExamplePostEnumParameter(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UsageExamplePostEnumParameter: %v", v)
	}
}

// UsageExamplePostOptEnumParameter - An enum type
type UsageExamplePostOptEnumParameter string

const (
	UsageExamplePostOptEnumParameterValue1 UsageExamplePostOptEnumParameter = "value1"
	UsageExamplePostOptEnumParameterValue2 UsageExamplePostOptEnumParameter = "value2"
	UsageExamplePostOptEnumParameterValue3 UsageExamplePostOptEnumParameter = "value3"
)

func (e UsageExamplePostOptEnumParameter) ToPointer() *UsageExamplePostOptEnumParameter {
	return &e
}

func (e *UsageExamplePostOptEnumParameter) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "value1":
		fallthrough
	case "value2":
		fallthrough
	case "value3":
		*e = UsageExamplePostOptEnumParameter(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UsageExamplePostOptEnumParameter: %v", v)
	}
}

type UsageExamplePostRequest struct {
	// A request body that contains fields with different formats for testing example generation
	RequestBody *UsageExamplePostRequestBody `request:"mediaType=application/json"`
	// A boolean parameter
	BoolParameter bool `queryParam:"style=form,explode=true,name=boolParameter"`
	// A date parameter
	DateParameter types.Date `queryParam:"style=form,explode=true,name=dateParameter"`
	// A date time parameter
	DateTimeParameter time.Time `queryParam:"style=form,explode=true,name=dateTimeParameter"`
	// A double parameter
	DoubleParameter float64 `queryParam:"style=form,explode=true,name=doubleParameter"`
	// An enum parameter
	EnumParameter UsageExamplePostEnumParameter `queryParam:"style=form,explode=true,name=enumParameter"`
	// A number parameter that contains a falsey example value
	FalseyNumberParameter float64 `queryParam:"style=form,explode=true,name=falseyNumberParameter"`
	// A float parameter
	FloatParameter float64 `queryParam:"style=form,explode=true,name=floatParameter"`
	// An int64 parameter
	Int64Parameter int64 `queryParam:"style=form,explode=true,name=int64Parameter"`
	// An integer parameter
	IntParameter int `queryParam:"style=form,explode=true,name=intParameter"`
	// An enum parameter
	OptEnumParameter *UsageExamplePostOptEnumParameter `queryParam:"style=form,explode=true,name=optEnumParameter"`
	// A string parameter
	StrParameter string `queryParam:"style=form,explode=true,name=strParameter"`
}

func (o *UsageExamplePostRequest) GetRequestBody() *UsageExamplePostRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *UsageExamplePostRequest) GetBoolParameter() bool {
	if o == nil {
		return false
	}
	return o.BoolParameter
}

func (o *UsageExamplePostRequest) GetDateParameter() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.DateParameter
}

func (o *UsageExamplePostRequest) GetDateTimeParameter() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.DateTimeParameter
}

func (o *UsageExamplePostRequest) GetDoubleParameter() float64 {
	if o == nil {
		return 0.0
	}
	return o.DoubleParameter
}

func (o *UsageExamplePostRequest) GetEnumParameter() UsageExamplePostEnumParameter {
	if o == nil {
		return UsageExamplePostEnumParameter("")
	}
	return o.EnumParameter
}

func (o *UsageExamplePostRequest) GetFalseyNumberParameter() float64 {
	if o == nil {
		return 0.0
	}
	return o.FalseyNumberParameter
}

func (o *UsageExamplePostRequest) GetFloatParameter() float64 {
	if o == nil {
		return 0.0
	}
	return o.FloatParameter
}

func (o *UsageExamplePostRequest) GetInt64Parameter() int64 {
	if o == nil {
		return 0
	}
	return o.Int64Parameter
}

func (o *UsageExamplePostRequest) GetIntParameter() int {
	if o == nil {
		return 0
	}
	return o.IntParameter
}

func (o *UsageExamplePostRequest) GetOptEnumParameter() *UsageExamplePostOptEnumParameter {
	if o == nil {
		return nil
	}
	return o.OptEnumParameter
}

func (o *UsageExamplePostRequest) GetStrParameter() string {
	if o == nil {
		return ""
	}
	return o.StrParameter
}

type UsageExamplePost200ApplicationJSONJSON struct {
	// A field called email that will have emails generated as examples
	Email *string `json:"email,omitempty"`
	// A field formatted as an email that will have emails generated as examples
	FormatEmail *string `json:"formatEmail,omitempty"`
	// A field formatted as a uri that will have uris generated as examples
	FormatURI *string `json:"formatUri,omitempty"`
	// A field formatted as a uuid that will have uuids generated as examples
	FormatUUID *string `json:"formatUuid,omitempty"`
	// A field formatted as a hostname that will have hostnames generated as examples
	Hostname *string `json:"hostname,omitempty"`
	// A field formatted as an ipv4 that will have ipv4s generated as examples
	Ipv4 *string `json:"ipv4,omitempty"`
	// A field formatted as an ipv6 that will have ipv6s generated as examples
	Ipv6 *string `json:"ipv6,omitempty"`
	// A simple object that uses all our supported primitive types and enums and has optional properties.
	SimpleObject *shared.SimpleObject `json:"simpleObject,omitempty"`
	// A field formatted as an unknown that will have random strings generated as examples
	Unknown *string `json:"unknown,omitempty"`
	// A field called uri that will have uris generated as examples
	URI *string `json:"uri,omitempty"`
	// A field called uuid that will have uuids generated as examples
	UUID *string `json:"uuid,omitempty"`
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetFormatEmail() *string {
	if o == nil {
		return nil
	}
	return o.FormatEmail
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetFormatURI() *string {
	if o == nil {
		return nil
	}
	return o.FormatURI
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetFormatUUID() *string {
	if o == nil {
		return nil
	}
	return o.FormatUUID
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetHostname() *string {
	if o == nil {
		return nil
	}
	return o.Hostname
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetIpv4() *string {
	if o == nil {
		return nil
	}
	return o.Ipv4
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetIpv6() *string {
	if o == nil {
		return nil
	}
	return o.Ipv6
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetSimpleObject() *shared.SimpleObject {
	if o == nil {
		return nil
	}
	return o.SimpleObject
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetUnknown() *string {
	if o == nil {
		return nil
	}
	return o.Unknown
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetURI() *string {
	if o == nil {
		return nil
	}
	return o.URI
}

func (o *UsageExamplePost200ApplicationJSONJSON) GetUUID() *string {
	if o == nil {
		return nil
	}
	return o.UUID
}

// UsageExamplePost200ApplicationJSON - A response body that contains the simpleObject sent in the request body
type UsageExamplePost200ApplicationJSON struct {
	JSON UsageExamplePost200ApplicationJSONJSON `json:"json"`
}

func (o *UsageExamplePost200ApplicationJSON) GetJSON() UsageExamplePost200ApplicationJSONJSON {
	if o == nil {
		return UsageExamplePost200ApplicationJSONJSON{}
	}
	return o.JSON
}

type UsageExamplePostResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A successful response that contains the simpleObject sent in the request body
	UsageExamplePost200ApplicationJSONObject *UsageExamplePost200ApplicationJSON
}

func (o *UsageExamplePostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UsageExamplePostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UsageExamplePostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UsageExamplePostResponse) GetUsageExamplePost200ApplicationJSONObject() *UsageExamplePost200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.UsageExamplePost200ApplicationJSONObject
}
