openapi: 3.0.3
info:
  title: OpenAPI Studio CLI API
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: "8080"
        description: The port number the CLI server is running on
paths:
  /health:
    get:
      summary: Health Check
      description: Check the CLI health and return relevant information.
      operationId: checkHealth
      responses:
        "200":
          $ref: "#/components/responses/HealthResponse"
  /run:
    get:
      summary: Get Last RunResult
      description: Get the output of the last run.
      operationId: getRun
      responses:
        "200":
          $ref: "#/components/responses/RunResponse"
    post:
      summary: Rerun generation
      description: Regenerate the currently selected targets.
      operationId: run
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/RunResponse"
  /overlays/compare:
    post:
      summary: Generate Overlay
      description: Generate an overlay from two yaml files
      operationId: generateOverlay
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OverlayCompareRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/OverlayCompareResponse"
  /suggest/method-names:
    get:
      summary: Suggest Method Names
      description: Suggest method names for the current source.
      operationId: suggestMethodNames
      responses:
        "200":
          $ref: "#/components/responses/SuggestResponse"
  /exit:
    post:
      summary: Exit
      description: Exit the CLI
      operationId: exit
      responses:
        "200":
          description: Successful response
components:
  responses:
    SuggestResponse:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              overlay:
                type: string
                description: The studio modifications overlay contents - this should be an overlay YAML document
            required:
              - overlay
    HealthResponse:
      description: Successful response
      content:
        text/event-stream:
          x-speakeasy-sse-sentinel: "[DONE]"
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the CLI
    RunResponse:
      description: Successful response
      content:
        text/event-stream:
          schema:
            type: object
            required:
              - event
              - data
            properties:
              event:
                type: string
                description: Type of the stream
              data:
                $ref: "#/components/schemas/RunResponseData"
    OverlayCompareResponse:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              overlay:
                type: string
                description: The studio modifications overlay contents - this should be an overlay YAML document
            required:
              - overlay
  schemas:
    RunRequestBody:
      type: object
      properties:
        overlay:
          type: string
          description: The studio modifications overlay contents - this should be an overlay YAML document
        input:
          type: string
          description: The input spec for the source
        targets:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/TargetSpecificInputs"
          description: |
            Map of target specific inputs keyed on target name
            Only present if a target input is modified
      required:
        - overlay
        - input
        - targets
    RunResponseData:
      type: object
      description: Map of target run summaries
      properties:
        step:
          type: string
          description: Step of the run
        isPartial:
          type: boolean
          description: Whether the run was partial
        lintingReportLink:
          type: string
          description: Link to the linting report
        sourceResult:
          $ref: "#/components/schemas/SourceResponseData"
        targetResults:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/TargetRunSummary"
          description: Map of target results
        workflow:
          $ref: "#/components/schemas/Workflow"
          description: Workflow information
        workingDirectory:
          type: string
          description: Working directory
        took:
          type: integer
          description: Time taken to run the workflow in milliseconds
        error:
          type: string
          description: Error message if the run failed
      required:
        - sourceResult
        - targetResults
        - workflow
        - workingDirectory
        - took
        - isPartial
        - step
    SourceResponseData:
      type: object
      properties:
        sourceID:
          type: string
          description: Source ID in the workflow file
        input:
          type: string
          description: The merged input specs for the source
        overlay:
          type: string
          description: Studio modifications overlay contents (could be empty string)
        overlayPath:
          type: string
          description: Studio modifications overlay path
        output:
          type: string
          description: Result of running the source in the workflow
        diagnosis:
          type: array
          items:
            $ref: "#/components/schemas/Diagnostic"
          description: List of validation errors
      required:
        - sourceID
        - input
        - overlay
        - overlayPath
        - output
    OverlayCompareRequestBody:
      type: object
      properties:
        before:
          type: string
          description: The first yaml file
        after:
          type: string
          description: The second yaml file
      required:
        - before
        - after
    TargetRunSummary:
      type: object
      properties:
        readme:
          type: string
          description: Contents of the README file for this target
        gen_yaml:
          type: string
          description: Contents of the gen.yaml file for this target
        gen_yaml_path:
          type: string
          description: The path to the gen.yaml file for this target
        output_directory:
          type: string
          description: Output directory for this target
        language:
          type: string
          description: Language for this target
        sourceID:
          type: string
          description: Source ID in the workflow file
        targetID:
          type: string
          description: Target ID in the workflow file
      required:
        - targetID
        - sourceID
        - readme
        - gen_yaml
        - output_directory
        - language
    TargetSpecificInputs:
      type: object
      properties:
        config:
          type: string
          description: New contents of the gen.yaml file for this target
      required:
        - config
    Workflow:
      type: object
      properties:
        version:
          type: string
          description: Workflow version
        speakeasyVersion:
          type: string
          description: Speakeasy version
        sources:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Source"
          description: Map of sources
        targets:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Target"
          description: Map of targets
      required:
        - version
        - speakeasyVersion
        - sources
        - targets
    Source:
      type: object
      properties:
        inputs:
          type: array
          items:
            $ref: "#/components/schemas/Document"
          description: List of input documents
        overlays:
          type: array
          items:
            $ref: "#/components/schemas/Overlay"
          description: List of overlays
        output:
          type: string
          description: Output string
        ruleset:
          type: string
          description: Ruleset string
        registry:
          $ref: "#/components/schemas/SourceRegistry"
          description: Source registry information
    Diagnostic:
      type: object
      properties:
        message:
          type: string
          description: Message describing the issue
        severity:
          type: string
          description: Severity
        line:
          type: integer
          description: Line number
        path:
          type: array
          items:
            type: string
          description: Schema path to the issue
        type:
          type: string
          description: Issue type
        helpMessage:
          type: string
          description: Help message for how to fix the issue
      required:
        - message
        - severity
        - type
    Document:
      type: object
      properties:
        location:
          type: string
          description: Document location
        auth:
          $ref: "#/components/schemas/Auth"
          description: Authentication information
      required:
        - location
    Overlay:
      type: object
      properties:
        fallbackCodeSamples:
          $ref: "#/components/schemas/FallbackCodeSamples"
          description: Fallback code samples
        document:
          allOf:
            - $ref: "#/components/schemas/Document"
            - type: object
              properties:
                contents:
                  type: string
                  description: Document contents
          description: Document information
    SourceRegistry:
      type: object
      properties:
        location:
          type: string
          description: Source registry location
        tags:
          type: array
          items:
            type: string
          description: List of tags
    Target:
      type: object
      properties:
        target:
          type: string
          description: Target language
        source:
          type: string
          description: Source ID
        output:
          type: string
          description: Output string
        publishing:
          $ref: "#/components/schemas/Publishing"
          description: Publishing information
        codeSamples:
          $ref: "#/components/schemas/CodeSamples"
          description: Code samples
      required:
        - target
        - source
    CodeSamples:
      type: object
      properties:
        output:
          type: string
          description: Output string
        registry:
          $ref: "#/components/schemas/SourceRegistry"
          description: Source registry information
    FallbackCodeSamples:
      type: object
    Auth:
      type: object
      properties:
        authHeader:
          type: string
          description: Auth header
        authSecret:
          type: string
          description: Auth secret
      required:
        - authHeader
        - authSecret
    Publishing:
      type: object
  securitySchemes:
    secret:
      type: apiKey
      name: x-secret-key
      in: header
security:
  - secret: []
