// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy/internal/studio/sdk/models/components"
)

type CancelRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *CancelRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
